### PR TITLE
Bump to v0.10.0 (KaTeX v0.16.7)

### PR DESCRIPTION
**Pull request by WozniakMac**
Updated KaTeX to v0.16.7

Backend rendering works fine. Tested. Rspec tests are fine too.
Haven't tested frontend part because I use it from cdn, not sprockets. But on first glance there wasn't any super breaking change here.

### CODE REVIEW

**Comment by glebm** [comment]
Did you use `rake update` to update? I'm a bit surprised that the fonts are completely unchanged

**Comment by glebm** [comment]
Looks like the fonts have remained the same for the past 2 years https://github.com/KaTeX/KaTeX/tree/main/fonts

**Comment by WozniakMac** [comment]
I did. It surprised me too 😄 . So I downloaded Katex release and copied fonts manually to be sure. No differences 🤷

**Comment by glebm** [comment]
Released v0.10.0

**Comment by WozniakMac** [comment]
Thanks!

**Pull request merged**
